[package]
name = "mas-storage"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.66"
chrono = "0.4.24"
thiserror = "1.0.39"
futures-util = "0.3.27"

apalis-core = { version = "0.4.0-alpha.4", features = ["tokio-comp"] }
rand_core = "0.6.4"
serde = "1.0.159"
serde_json = "1.0.95"
url = "2.3.1"
ulid = "1.0.0"

oauth2-types = { path = "../oauth2-types" }
mas-data-model = { path = "../data-model" }
mas-iana = { path = "../iana" }
mas-jose = { path = "../jose" }
