[package]
name = "mas-tasks"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.70"
apalis-core = { version = "0.4.0-alpha.4", features = ["extensions", "tokio-comp"] }
apalis-cron = "0.4.0-alpha.4"
apalis-sql = { version = "0.4.0-alpha.4", features = ["postgres", "tokio-comp"] }
async-trait = "0.1.66"
chrono = "0.4.24"
rand = "0.8.5"
rand_chacha = "0.3.1"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres"] }
thiserror = "1.0.30"
tower = "0.4.13"
tracing = "0.1.37"
tracing-opentelemetry = "0.18.0"
opentelemetry = "0.18.0"
ulid = "1.0.0"
serde = { version = "1.0.159", features = ["derive"] }

mas-storage = { path = "../storage" }
mas-storage-pg = { path = "../storage-pg" }
mas-email = { path = "../email" }
mas-data-model = { path = "../data-model" }
